name: Build and Publish CoAP.NET package
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release  --version-suffix pre-${{ github.run_number }}
      
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            CoAP.NET/bin/Release/

      - name: Publish package to NuGet
        run: |
          cd CoAP.NET/bin/Release
          dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_KEY }}  --source https://api.nuget.org/v3/index.json  